# This workflow will:
# - compile project on windows, linux, macos with JDK 8
# - run sonar on linux

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        jdk: [8]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}
      AUDIODEV: "null"

    steps:
     - name: Checkout
       uses: actions/checkout@v3.5.0

     - name: Cache
       uses: actions/cache@v3.3.1
       with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-java${{ matrix.jdk }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-java${{ matrix.jdk }}-
            maven-${{ matrix.os }}-

     - name: JDK
       uses: actions/setup-java@v3.11.0
       with:
         java-version: |
           ${{ env.JDK_VERSION }}
           17
         distribution: 'temurin'
         mvn-toolchain-id: |
           JavaSE-1.8
           JavaSE-17

     - name: Compile
       if: matrix.os != 'windows-latest'
       uses: coactions/setup-xvfb@v1
       with:
         run: mvn clean install --file lionheart-parent/pom.xml -U -Ppc-assets

     - name: Sonar
       if: matrix.os == 'windows-latest'
       uses: coactions/setup-xvfb@v1
       with:
         run: mvn clean install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file lionheart-parent/pom.xml -U -Ppc-assets -Dsonar.organization=b3dgs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=b3dgs_lionheart-remake
