# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        jdk: [8]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}
      AUDIODEV: "null"
    
    steps:
     - name: Checkout
       uses: actions/checkout@v3.5.0
     
     - name: Cache
       uses: actions/cache@v3.3.1
       with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-java${{ matrix.jdk }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-java${{ matrix.jdk }}-
            maven-${{ matrix.os }}-
     
     - name: Set JDK
       uses: actions/setup-java@v3.11.0
       with:
         java-version: |
           ${{ env.JDK_VERSION }}
           17
         distribution: 'temurin'
         mvn-toolchain-id: |
           JavaSE-1.8
           JavaSE-17
     
     - name: Compile
       uses: coactions/setup-xvfb@v1
       with:
         run: mvn clean install --file lionheart-parent/pom.xml -U -Ppc-assets
