# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        jdk: [8]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}
      AUDIODEV: "null"
    
    steps:
     - name: Checkout Repo
       uses: actions/checkout@v2
     
     - name: Cache Maven packages
       uses: actions/cache@v2.1.1
       with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-java${{ matrix.jdk }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-java${{ matrix.jdk }}-
            maven-${{ matrix.os }}-
     
     - name: Install Toolchain JDK
       if: ${{ matrix.jdk == '8' }}
       uses: battila7/jdk-via-jabba@v1
       with:
          jdk: openjdk@1.17.0
          javaHomeEnvironmentVariable: TOOLCHAIN_JDK
     
     - name: Set up Toolchain
       if: ${{ matrix.jdk == '8' }}
       shell: bash
       run: |
          mkdir -p $HOME/.m2 \
          && cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
                <provides>
                  <version>17</version>
                  <vendor>temurin</vendor>
                </provides>
                <configuration>
                  <jdkHome>${{ env.TOOLCHAIN_JDK }}</jdkHome>
                </configuration>
            </toolchain>
          </toolchains>
          EOF
     
     - name: Set up JDK
       uses: actions/setup-java@v2
       with:
         java-version: ${{ matrix.jdk }}
         distribution: 'temurin'
     
     - name: Run build
       uses: GabrielBB/xvfb-action@v1
       with:
         run: mvn clean install --file lionheart-parent/pom.xml -U -Ppc-assets
